### ISSUE TITLE
Problem machines for the upcoming July release

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2662]
[test-docker-fedora34-x64-1](https://ci.adoptopenjdk.net/computer/test-docker-fedora34-x64-1/) and (newly created) [test-docker-fedora34-x64-2](https://ci.adoptopenjdk.net/computer/test-docker-fedora34-x64-2/) ref https://github.com/adoptium/infrastructure/issues/2631 

The following tests are failing on both -1 and -2. Links are for -2
java/nio/file/Files/probeContentType/Basic.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5133/console
java/net/Inet6Address/B6206527.java.B6206527
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5135/console
java/net/ipv6tests/B6521014.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5136/console

[test-osuosl-centos74-ppc64le-1/](https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-1/) and [test-osuosl-centos74-ppc64le-2/](https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-2/) ref https://github.com/adoptium/infrastructure/issues/2625

test-osuosl-centos74-ppc64le-1

sun/security/pkcs11/fips/TestTLS12.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5092/console

sun/tools/jinfo/Basic.sh
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5094/console

test-osuosl-centos74-ppc64le-2

sun/security/pkcs11/fips/TestTLS12.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5095/console

sun/tools/jinfo/Basic.sh
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5103/console

[test-azure-win2012r2-x64-3](https://ci.adoptopenjdk.net/computer/test-azure-win2012r2-x64-3/) and [test-azure-win2019-x64-1](https://ci.adoptopenjdk.net/computer/test-azure-win2019-x64-1/) ref https://github.com/adoptium/infrastructure/issues/2645

**Comment by sophia-guo** [comment]
ERROR: Cannot delete workspace :Malformed input or input contains  unmappable characters https://github.com/adoptium/infrastructure/issues/2630

**Comment by sophia-guo** [comment]
[test-azure-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/test-azure-win2012r2-x64-1/) 

`ERROR: Cannot delete workspace :Unable to delete 'D:\jenkins\workspace\Test_openjdk11_hs_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image\lib\modules'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.`

Recent two run:
https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-64_windows/647/console
https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-64_windows/647/console

**Comment by Haroon-Khel** [comment]
That directory is being used by a leftover jcmd.exe process
<img width="921" alt="image" src="https://user-images.githubusercontent.com/34969545/179019832-8e5ebd3c-4970-4dcf-b309-e5cc96ae53f5.png">

https://github.com/adoptium/infrastructure/issues/2635 is related. It is surprising to find that this is occurring on a different machine this time

**Comment by Haroon-Khel** [comment]
sun/tools/jinfo/Basic.sh on the 2 ppc64le machines has been resolved, https://github.com/adoptium/infrastructure/issues/2625#issuecomment-1181699740

**Comment by sophia-guo** [comment]
[test-azure-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/test-azure-win2012r2-x64-1/)

https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-64_windows/647/console

```
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
ERROR: Cannot delete workspace :Unable to delete 'D:\jenkins\workspace\Test_openjdk11_hs_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image\lib\modules'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
Exception: hudson.AbortException: Cannot delete workspace: Unable to delete 'D:\jenkins\workspace\Test_openjdk11_hs_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image\lib\modules'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.

```

**Comment by sxa** [comment]
> [test-azure-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/test-azure-win2012r2-x64-1/)
> 
> https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-64_windows/648/console https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-64_windows/647/console https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-64_windows/646/console
> 
> ```
> [WS-CLEANUP] Deleting project workspace...
> [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
> ERROR: Cannot delete workspace :Unable to delete 'D:\jenkins\workspace\Test_openjdk11_hs_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image\lib\modules'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
> [Pipeline] }
> [Pipeline] // timeout
> [Pipeline] echo
> Exception: hudson.AbortException: Cannot delete workspace: Unable to delete 'D:\jenkins\workspace\Test_openjdk11_hs_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image\lib\modules'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
> ```
> 
> All three recent jobs are assigned to this machine and failed . all failed with running this specific machine

Fixed as per https://github.com/adoptium/infrastructure/issues/2209#issuecomment-1185341489

**Comment by Haroon-Khel** [comment]
Machines that are still problematic:

**Any fedora dockerstatic container**. ref https://github.com/adoptium/infrastructure/issues/2631, any fedora container on https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu2004-intel-1/ will pass ipv6 tests while those on https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu2004-amd-1/ will fail them. The difference needs to be investigated. 
I cant get java/nio/file/Files/probeContentType/Basic.java to pass on Fedora, see https://github.com/adoptium/infrastructure/issues/2631#issuecomment-1185690200


**test-osuosl-centos74-ppc64le-1 and -2**
sun/tools/jinfo/Basic.sh now passes, but sun/security/pkcs11/fips/TestTLS12.java still fails. See https://github.com/adoptium/infrastructure/issues/2625#issuecomment-1181699740

**test-azure-win2012r2-x64-3 and test-azure-win2019-x64-1** 
see https://github.com/adoptium/infrastructure/issues/2645#issuecomment-1177334175
Failures are intermittent, but more failures than passes.

If by Monday these issues are not resolved, I'll turn the jenkins nodes offline for the release

**Comment by Haroon-Khel** [comment]
I was able to get java/nio/file/Files/probeContentType/Basic.java to pass on our fedora boxes, see https://github.com/adoptium/infrastructure/issues/2631#issuecomment-1188992683, however I have not solved the failing ipv6 tests on fedora containers hosted on https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu2004-amd-1/.

And sun/security/pkcs11/fips/TestTLS12.java continues to fail on test-osuosl-centos74-ppc64le-1 and -2, see https://github.com/adoptium/infrastructure/issues/2625

I have temporarily turned offline the following nodes for this release

https://ci.adoptopenjdk.net/computer/test-docker-fedora34-x64-1/
https://ci.adoptopenjdk.net/computer/test-docker-fedora34-x64-2/
https://ci.adoptopenjdk.net/computer/test-docker-fedora36-x64-1/
https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-1/
https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-2/

**Comment by Haroon-Khel** [comment]
> https://ci.adoptopenjdk.net/computer/test-docker-fedora34-x64-1/
https://ci.adoptopenjdk.net/computer/test-docker-fedora34-x64-2/
https://ci.adoptopenjdk.net/computer/test-docker-fedora36-x64-1/
https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-1/
https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-2/

I've turned these machines back online

**Comment by sxa** [comment]
@Haroon-Khel Can you give a status update on the systems that were problematic - have they all now been resolved or is there still work to do here. Need to know whether it can be closed or whether it needs to move to October.

**Comment by Haroon-Khel** [comment]
Since sun/security/pkcs11/fips/TestTLS12.java continues to fail on test-osuosl-centos74-ppc64le-1 and -2 this issue should be kept open

**Comment by sxa** [comment]
Related: https://github.com/adoptium/infrastructure/issues/2815

**Comment by Haroon-Khel** [comment]
Ipv6 failures on new ppc64le machine https://github.com/adoptium/infrastructure/issues/2883
test-docker-ubuntu2204-ppc64le-1
test-docker-debian11-ppc64le-1
Could also affect:
test-docker-ubuntu2204-ppc64le-2
test-docker-debian11-ppc64le-2
test-docker-debian11-ppc64le-3

https://github.com/adoptium/infrastructure/blob/952a0bddf784ddcae519661daf975f1abb693ec4/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml#L6 has run on the machines during setup, annoyingly it isn't fixing the problem

**Comment by Haroon-Khel** [comment]
ref https://github.com/adoptium/infrastructure/issues/2886

Taking test-docker-centos8-x64-2 offline

**Comment by Haroon-Khel** [comment]
Taking offline the following machines due to https://github.com/adoptium/infrastructure/issues/2884

test-docker-ubuntu2204-ppc64le-1
test-docker-debian11-ppc64le-1
test-docker-ubuntu2204-ppc64le-2
test-docker-debian11-ppc64le-2

**Comment by Haroon-Khel** [comment]
https://ci.adoptopenjdk.net/computer/test-docker-centos8-x64-2/ is offline ref https://github.com/adoptium/infrastructure/issues/2886

**Comment by Haroon-Khel** [comment]
ref https://github.com/adoptium/infrastructure/issues/2885 test-ibmcloud-win2012r2-x64-1 offline

**Comment by Haroon-Khel** [comment]
These need to be addressed https://github.com/adoptium/adoptium/issues/200#issuecomment-1402131107

**Comment by Haroon-Khel** [comment]
> test-docker-ubi8-x64-2 and test-docker-fedora35-x64-1 both offline ref https://github.com/adoptium/infrastructure/issues/2882

Closed off https://github.com/adoptium/infrastructure/issues/2882

**Comment by sxa** [comment]
@Haroon-Khel There seems to be quite a few test-docker machines that are in jenkins but not live, for example https://ci.adoptium.net/manage/computer/test%2Ddocker%2Dfedora37%2Darmv8%2D1/ - should they be removed from jenkins now? That one in particular seems to be the latest Fedora version so I'm a little surprised if it has been removed.

**Comment by sxa** [comment]
s390x issues:
- https://github.com/adoptium/infrastructure/issues/2807
- https://github.com/adoptium/infrastructure/issues/3170

**Comment by sxa** [comment]
Also we've been having some inconsistencies on test issues in https://github.com/adoptium/infrastructure/issues/2536 across different mac machines.

**Comment by sxa** [comment]
extended.perf `dacapo-xalan-0` success varies depending on machine: https://github.com/adoptium/aqa-tests/issues/3122#issuecomment-1787036636

**Comment by jiekang** [comment]
Data from the October CPU AQA triage can be found here:
https://docs.google.com/spreadsheets/d/16vAQvYzL_-azDoD5OhQ6lObD3-suJwqKfjtABuWoIkc/edit#gid=1601438678

This has a summary sheet, and a sheet for JDK Version with a list of: suite failures, action taken, and if applicable, problematic machine and failure type. 

This list should be used to help drive individual actions to improve test infrastructure and reduce the number of re-runs due to machine configuration related issues. The rows that have a 'Bad Machine' and 'Failure Type' listed should be investigated first.

There is also a list of 'To Investigate' topics in each JDK Version sheet that may not necessarily be machine configuration issues, but look promising to me to understand and resolve. When I get more cycles, I intend to open separate, individual issues for these in the appropriate repos.

**Comment by Haroon-Khel** [comment]
**JDK17**

test-docker-ubuntu2004-armv8l-3
- jdk_imageio and jdk_beans
- https://ci.adoptium.net/view/Test_grinder/job/Grinder/8270/console
- Consistent failures:
jdk_beans
```
TEST: java/beans/PropertyChangeSupport/Test4682386.java
TEST: java/beans/PropertyEditor/TestFontClassJava.java
TEST: java/beans/PropertyEditor/TestFontClassValue.java
TEST: java/beans/XMLEncoder/javax_swing_DefaultCellEditor.java
TEST: java/beans/XMLEncoder/javax_swing_JTree.java
TEST: java/beans/XMLEncoder/Test4631471.java
TEST: java/beans/XMLEncoder/Test4903007.java
```
jdk_imageio
```
TEST: javax/imageio/plugins/shared/ImageWriterCompressionTest.java
```

test-docker-ubuntu2010-armv8l-2
- jdk_imageio
- https://ci.adoptium.net/view/Test_grinder/job/Grinder/8271/console
- Consistent failure:
```
TEST: javax/imageio/plugins/shared/ImageWriterCompressionTest.java
```

test-docker-sles12-s390x-1
- jdk_beans
- https://ci.adoptium.net/view/Test_grinder/job/Grinder/8273/console
- Consistent failures:
```
TEST: java/beans/PropertyChangeSupport/Test4682386.java
TEST: java/beans/PropertyEditor/TestFontClassJava.java
TEST: java/beans/PropertyEditor/TestFontClassValue.java
TEST: java/beans/XMLEncoder/javax_swing_DefaultCellEditor.java
TEST: java/beans/XMLEncoder/javax_swing_JTree.java
TEST: java/beans/XMLEncoder/Test4631471.java
TEST: java/beans/XMLEncoder/Test4903007.java
```

test-marist-ubuntu2204-s390x-1
- jdk_management_1
- https://ci.adoptium.net/view/Test_grinder/job/Grinder/8278/console

test-docker-fedora33-ppc64le-1
- jdk_nio_1
- https://ci.adoptium.net/view/Test_grinder/job/Grinder/8279/console

test-skytap-ubuntu2004-ppc64le-1
- jvm_compiler_1
- https://ci.adoptium.net/view/Test_grinder/job/Grinder/8280/console

**Comment by Haroon-Khel** [comment]
**JDK21**

test-docker-centos8-x64-1
- https://ci.adoptium.net/view/Test_grinder/job/Grinder/8311/console
- jdk_lang
```
TEST: java/lang/ProcessHandle/InfoTest.java
TEST: java/lang/reflect/Proxy/ClassRestrictions.java
TEST: java/lang/runtime/SwitchBootstrapsTest.java
TEST: java/lang/ScopedValue/UnboundValueAfterOOME.java
TEST: java/lang/String/RegionMatches.java
TEST: java/lang/System/LoggerFinder/RecursiveLoading/PlatformRecursiveLoadingTest.java
TEST: java/lang/System/LoggerFinder/RecursiveLoading/RecursiveLoadingTest.java
TEST: java/lang/System/LoggerFinder/SignedLoggerFinderTest/SignedLoggerFinderTest.java
```

test-docker-debian11-ppc64le-2
- https://ci.adoptium.net/view/Test_grinder/job/Grinder/8346/console

test-docker-debian11-ppc64le-1
- https://ci.adoptium.net/view/Test_grinder/job/Grinder/8347/console

**Comment by sxa** [comment]
List of likely machine related tests which I'm giong to stop bumping between iterations so we can track based on their attachment to this issue:

RHEL/CentOS*:
- https://github.com/adoptium/infrastructure/issues/2900
- https://github.com/adoptium/infrastructure/issues/2360
- https://github.com/adoptium/infrastructure/issues/1829
- https://github.com/adoptium/infrastructure/issues/2886
- https://github.com/adoptium/infrastructure/issues/1750

AIX:
- https://github.com/adoptium/infrastructure/issues/2457
- https://github.com/adoptium/infrastructure/issues/2516
- https://github.com/adoptium/infrastructure/issues/3178

Linux/s390x:
- https://github.com/adoptium/infrastructure/issues/2869
- https://github.com/adoptium/infrastructure/issues/2807
- https://github.com/adoptium/infrastructure/issues/3189

- https://github.com/adoptium/infrastructure/issues/2163
- https://github.com/adoptium/infrastructure/issues/2514

**Comment by sxa** [comment]
List of test failures on JDK8/arm32 (at a minimum) including the `perf` test suites which are failing in the containerised environments on the arm64 hosts, but are ok on the two physical ODROID machines:
https://github.com/adoptium/infrastructure/issues/3043
